document
  .querySelector(".estimation-form")
  .addEventListener("submit", async function (e) {
    e.preventDefault();

    // Récupérer les données du formulaire
    const data = {
      marque: e.target.marque.value,
      modele: e.target.modele.value,
      annee: e.target.annee.value,
      kilometrage: e.target.kilometrage.value,
      carburant: e.target.carburant.value,
      boite: e.target.boite.value,
    };

    //valeurs par defaults
    const labels_defaults = {
      marque : "Quelle est la marque de votre voiture ?",
      modele : "Quelle est le modele de votre voiture ?",
      kilometrage : "Quelle est le kilométrage ?",

    }
      const warning = document.querySelector("#info")


    //valider le formulaire 
    if(data.marque=== labels_defaults.marque || data.modele === labels_defaults.modele || data.kilometrage === labels_defaults.kilometrage  ){
      warning.classList.add('info_w')
      warning.textContent = "Toutes les champs sont obligatoire"
      warning.classList.toggle('active')

    }else{
       try {
      // trouver le prix  aux BDD
      const response = await fetch("https://cotav-back.onrender.com/estimation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });

      //recuprer  les resultats sous forme de JSON
      const result = await response.json();
     console.log(result)
      //traiter  les resultats 
      if(result.code===400){
      }else if(result.code = 200){
       const resultat = document.querySelector('.estimation-result')
       resultat.classList.add('active')
       
        resultat.querySelector("h4").textContent = `Notre estimation : ${result.moyenne} Dh `
        
      }
     
      //capter l'erreur
    } catch (error) {
      console.error("Erreur de connexion :", error);
    }
    }

   
  });





const dict_marque_modele = {
  AC: ["GT40"],
  Abarth: ["124 Spider", "595", "695"],
  "Alfa Romeo": [
    "146",
    "147",
    "155",
    "156",
    "159",
    "166",
    "4C",
    "8C",
    "Brera",
    "GT",
    "Giulia",
    "Giulietta",
    "MiTo",
    "Stelvio",
    "Tonale",
  ],
  Audi: [
    "80",
    "A1",
    "A2",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4",
    "Q5",
    "Q7",
    "Q8",
    "R8",
    "TT",
    "V8",
  ],
  Autre: ["Autres"],
  BMW: [
    "Série 1",
    "Série 2",
    "Série 3",
    "Série 4",
    "Série 5",
    "Série 6",
    "Série 7",
    "Série 8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "XM",
    "Z3",
    "Z4",
    "i3",
    "i3s",
    "iX",
  ],
  BYD: ["F0", "F1", "F3", "Seal U"],
  Bentley: ["Arnage", "Bentayga", "Continental T", "Flying Spur"],
  Cadillac: [
    "Allente",
    "BLS",
    "Brougham",
    "CTS",
    "Escalade",
    "Fleetwood",
    "SLS",
  ],
  Chana: ["5", "Shenqi"],
  Changan: ["Alsvin", "CS35", "CS55"],
  Changhe: ["Ideal"],
  Chery: [
    "A1",
    "A113",
    "A3",
    "A5",
    "Eastar",
    "QQ",
    "Tiggo",
    "Tiggo 2 Pro",
    "Tiggo 4 Pro",
    "Tiggo 7 Pro",
    "V",
  ],
  Chevrolet: [
    "Alero",
    "Astro",
    "Avalanche",
    "Aveo",
    "Beretta",
    "CMP",
    "Camaro",
    "Caprice",
    "Captiva",
    "Corvette",
    "Cruze",
    "HHR",
    "Kalos",
    "Optra",
    "Orlando",
    "Spark",
    "Tahoe",
  ],
  Chrysler: ["300", "Grand Voyager", "Pacifica", "Sebring"],
  Citroën: [
    "2 CV",
    "AX",
    "Ami",
    "BX",
    "Berlingo",
    "C-Elysée",
    "C-crosser",
    "C1",
    "C15",
    "C2",
    "C3",
    "C35",
    "C4",
    "C5",
    "C6",
    "C8",
    "CX",
    "Evasion",
    "Jumper",
    "Jumpy",
    "Nemo",
    "SM",
    "Saxo",
    "Spacetourer",
    "Visa",
    "Xantia",
    "Xsara",
    "ZX",
    "c4x",
  ],
  Cupra: ["Ateca", "Formentor", "Leon"],
  DFSK: [
    "3",
    "C31",
    "Glory 500",
    "Glory 580",
    "Glory IX5",
    "K01h",
    "K01l",
    "K01s",
    "Mini Bus",
    "Super Cab",
  ],
  DS: ["100", "7 LIGNE OR", "DS", "DS 3", "DS 4", "DS 5", "DS6", "ds7"],
  Dacia: [
    "Arkana",
    "Bigster",
    "Dokker",
    "Duster",
    "Jogger",
    "Lodgy",
    "Logan",
    "Pick-Up",
    "Sandero",
    "Solenza",
    "Spring",
  ],
  Daewoo: [
    "Applause",
    "Espero",
    "Evanda",
    "Kalos",
    "Korando",
    "Lacetti",
    "Lanos",
    "Matiz",
    "Nubira",
  ],
  Daihatsu: ["Copen", "Cuore", "Move", "Sirion", "Terios", "YRV"],
  Dodge: ["Avenger", "Caliber", "Challenger"],
  FAW: ["X40"],
  Ferrari: ["California", "Mondial"],
  Fiat: [
    "126",
    "127",
    "131",
    "500",
    "500 C",
    "500 L",
    "500 X",
    "600",
    "600 E",
    "600e",
    "Albea",
    "Bertone",
    "Brava",
    "Bravo",
    "Burstner",
    "Coupe",
    "Croma",
    "Doblo",
    "Ducato",
    "Fiorino",
    "Freemont",
    "Fullback",
    "Grande Punto",
    "Linea",
    "Marea",
    "Multipla",
    "Palio",
    "Panda",
    "Punto",
    "Regata",
    "Ritmo",
    "Scudo",
    "Siena",
    "Stilo",
    "Talento",
    "Tempra",
    "Tipo",
    "Ulysse",
    "Uno",
  ],
  Force: ["Traveller"],
  Ford: [
    "B Max",
    "Bedford",
    "C Max",
    "Connect",
    "Cougar",
    "Courrier",
    "E-350",
    "Ecosport",
    "Edge",
    "Escort",
    "Everest",
    "Expedition",
    "F-150",
    "F-350",
    "Fiesta",
    "Focus",
    "Fusion",
    "GT",
    "Galaxy",
    "Ka",
    "Kuga",
    "Mondeo",
    "Mustang",
    "Pick-Up",
    "Ranger",
    "S-Max",
    "Sierra",
    "TM",
    "Tourneo Connect",
    "Transit",
    "Victoria",
    "raptor",
  ],
  Foton: ["Forland", "TM"],
  GMC: ["Hover", "Yukon"],
  GWM: ["Florid Cross", "Haval H6", "POER", "haval jolion"],
  Geely: ["CK", "Coolray", "GX3 Pro", "LC", "MK", "X40"],
  HUMMER: ["H2", "H3"],
  Hafei: ["Minyi", "Zhongyi"],
  Honda: [
    "Accord",
    "Acty",
    "Boss",
    "CR-V",
    "Carry",
    "City",
    "Civic",
    "Concerto",
    "HR-V",
    "Jazz",
    "Legend",
    "Logo",
    "NSX",
    "Odyssey",
    "Prelude",
  ],
  Hyundai: [
    "Accent",
    "Atos",
    "Bayon",
    "Centennial",
    "County",
    "Coupe",
    "Creta",
    "Elantra",
    "Equus",
    "Excel",
    "Galloper",
    "Genesis",
    "Getz",
    "H",
    "H-200",
    "H1",
    "H100",
    "IONIQ",
    "IONIQ 5",
    "Kona",
    "Lantra",
    "Santa Fe",
    "Santamo",
    "Satellite",
    "Sonata",
    "Sonica",
    "Staria",
    "Terracan",
    "Tucson",
    "Veloster",
    "Veracruz",
    "XG",
    "i10",
    "i20",
    "i30",
    "i40",
    "ix35",
    "ix55",
  ],
  Infiniti: ["FX35", "FX45", "QX70"],
  Isuzu: ["D-Max", "Landwind", "Super Carry", "TFR Pick-up", "Trooper"],
  Iveco: ["35c", "Daily"],
  Jaguar: ["420G", "E-Pace", "F-Pace", "S-Type", "X-Type", "XE", "XF", "XJ"],
  Jeep: [
    "Avenger",
    "Cherokee",
    "Commander",
    "Compass",
    "Grand Cherokee",
    "Patriot",
    "Renegade",
    "Wrangler",
  ],
  Jonway: ["UFO"],
  Kia: [
    "Besta",
    "Carens",
    "Carnival",
    "Ceed",
    "Cerato",
    "Fiesta",
    "K 2500",
    "K 2700",
    "K5",
    "Mohave",
    "Niro",
    "Opirus",
    "Optima",
    "Picanto",
    "Pregio",
    "Proceed",
    "Rio",
    "Seltos",
    "Sephia",
    "Shuma",
    "Sonet",
    "Sorento",
    "Soul",
    "Sportage",
    "Stinger",
  ],
  Lamborghini: ["Jalpa", "Reventon"],
  Lancia: ["Dedra", "Delta", "Phedra", "Thema", "Ypsilon"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
    "Range Rover Vogue",
    "Santana",
  ],
  Lexus: ["ES", "GS", "IS", "LS", "NX", "RX", "UX"],
  Lincoln: ["Town Car"],
  Llifan: ["320"],
  MG: ["HS", "MG HS", "MG3", "MG4", "MG5", "Marvel R", "ZS"],
  Mahindra: ["Goa", "Hover", "KUV 100", "Scorpio", "XUV 500"],
  Maserati: ["Ghibli", "Levante", "Quattroporte"],
  Mazda: [
    "2",
    "3",
    "323",
    "5",
    "6",
    "BT50",
    "CX-3",
    "CX-5",
    "CX-7",
    "CX-9",
    "MX-3",
    "MX-5",
    "MX-6",
  ],
  McLaren: ["GT"],
  "Mercedes-Benz": [
    "180",
    "190",
    "200",
    "207D",
    "210",
    "220",
    "230",
    "240",
    "250",
    "260",
    "270",
    "280",
    "300",
    "307",
    "309",
    "310D",
    "400",
    "408",
    "410",
    "412",
    "500",
    "608",
    "AMG GT",
    "AMG GTC",
    "AMG GTS",
    "Citan",
    "Classe A",
    "Classe B",
    "Classe C",
    "Classe CL",
    "Classe CLA",
    "Classe CLC",
    "Classe CLK",
    "Classe CLS",
    "Classe E",
    "Classe G",
    "Classe GLA",
    "Classe GLC",
    "Classe GLE",
    "Classe GLK",
    "Classe GLS",
    "Classe ML",
    "Classe S",
    "Classe SL",
    "Classe SLK",
    "Classe SLS",
    "Classe V",
    "EQE",
    "GLB",
    "SSK",
    "Sprinter",
    "Vaneo",
    "Vario",
    "Viano",
    "Vito",
  ],
  Mini: [
    "Austin",
    "Clubman",
    "Cooper",
    "Countryman",
    "Hatch",
    "One",
    "Paceman",
    "Roadster",
  ],
  Mitsubishi: [
    "3000",
    "Colt",
    "Galant",
    "Grandis",
    "L200",
    "Lancer",
    "Nativa",
    "Outlander",
    "Pajero",
    "Pick Up",
    "Sportero",
  ],
  Nissan: [
    "240 SX",
    "280",
    "300",
    "350 Z",
    "Almera",
    "Cabstar",
    "Evalia",
    "GTR",
    "Juke",
    "Kicks",
    "Kubistar",
    "Maxima",
    "Micra",
    "Murano",
    "Navara",
    "Note",
    "Pathfinder",
    "Patrol",
    "Pick Up",
    "Primera",
    "Qashqai",
    "Rogue",
    "Sentra",
    "Serena",
    "Sunny",
    "Terrano",
    "Tiida",
    "Urvan",
    "Vanette",
    "X-Trail",
  ],
  Opel: [
    "Adam",
    "Agila",
    "Antara",
    "Astra",
    "Calibra",
    "Campo",
    "Combo",
    "Corsa",
    "Crossland",
    "Frontera",
    "GT",
    "Grandland",
    "Insignia",
    "Kadett",
    "Meriva",
    "Mokka",
    "Movano",
    "Omega",
    "Sintra",
    "Tigra",
    "Vectra",
    "Zafira",
  ],
  Peugeot: [
    "1007",
    "104",
    "106",
    "107",
    "108",
    "2008",
    "203",
    "204",
    "205",
    "206",
    "207",
    "208",
    "3008",
    "301",
    "305",
    "306",
    "307",
    "308",
    "309",
    "4007",
    "4008",
    "403",
    "404",
    "405",
    "406",
    "407",
    "5008",
    "504",
    "505",
    "508",
    "607",
    "806",
    "807",
    "Bipper",
    "Boxer",
    "Expert",
    "J5",
    "J9",
    "Landtrek",
    "Partner",
    "Pick-up",
    "RCZ",
    "Rifter",
  ],
  Pontiac: ["Solstice"],
  Porsche: [
    "718 Cayman",
    "911",
    "Boxster",
    "Cayenne",
    "Cayman",
    "Macan",
    "Panamera",
  ],
  Renault: [
    "12",
    "14",
    "16",
    "30",
    "Arkana",
    "Austral",
    "Avantime",
    "B 110",
    "Captur",
    "Clio",
    "Espace",
    "Estafette",
    "Express",
    "Fluence",
    "Fuego",
    "Kadjar",
    "Kangoo",
    "Kardian",
    "Koleos",
    "Laguna",
    "Latitude",
    "Mascott",
    "Master",
    "Megane",
    "Modus",
    "Nevada",
    "R11",
    "R18",
    "R19",
    "R21",
    "R25",
    "R4",
    "R5",
    "R8",
    "R9",
    "Safrane",
    "Samsung SM3",
    "Scenic",
    "Super 5",
    "Symbol",
    "Talisman",
    "Trafic",
    "Twingo",
    "Twizy",
    "Vel Satis",
    "Zoe",
  ],
  "Rolls-Royce": ["Silver Wraith"],
  Rover: [
    "214",
    "25",
    "45",
    "75",
    "Mini",
    "Série 200",
    "Série 400",
    "Série 600",
  ],
  Seat: [
    "Alhambra",
    "Altea",
    "Arona",
    "Arosa",
    "Ateca",
    "Cordoba",
    "Ibiza",
    "Inca",
    "Leon",
    "Mii",
    "Tarraco",
    "Toledo",
  ],
  Seres: ["Seres 3"],
  Skoda: [
    "Fabia",
    "Felicia",
    "Kamiq",
    "Karoq",
    "Kodiaq",
    "Octavia",
    "Rapid",
    "Roomster",
    "Scala",
    "Superb",
    "Yeti",
  ],
  Smart: ["Brabus", "ForTwo"],
  Ssangyong: [
    "Actyon",
    "Family",
    "Korando",
    "Kyron",
    "Rexton",
    "Rodius",
    "Stavic",
    "Tivoli",
    "XLV",
  ],
  Subaru: ["Impreza", "Legacy", "Tribeca"],
  Suzuki: [
    "APV",
    "Aerio",
    "Alto",
    "Baleno",
    "Carry",
    "Celerio",
    "Grand Vitara",
    "Ignis",
    "Jimny",
    "Liana",
    "Maruti",
    "S-Cross",
    "SX-4",
    "Samurai",
    "Splash",
    "Swift",
    "Vitara",
    "Wagon R",
    "X-90",
  ],
  TVR: ["Cerbera"],
  Tata: ["Super Ace", "Xenon"],
  Tesla: ["Model 3", "Model 4", "Model 5", "Model Y"],
  Toyota: [
    "4 Runner",
    "Auris",
    "Avensis",
    "Aygo",
    "C-HR",
    "Celica",
    "Corolla",
    "Corolla X SUV",
    "Corona",
    "Fortuner",
    "HiAce",
    "Hilux",
    "Land Cruiser",
    "Lexus",
    "MR",
    "Prado",
    "Prius",
    "RAV-4",
    "Starlet",
    "Supra",
    "Tercel",
    "Verso",
    "Yaris",
  ],
  Volkswagen: [
    "Amarok",
    "Arteon",
    "Bora",
    "Caddy",
    "Caravelle",
    "Coccinelle",
    "Combi",
    "Crafter",
    "E-Golf",
    "Eos",
    "Fox",
    "Gol",
    "Golf 1",
    "Golf 2",
    "Golf 3",
    "Golf 4",
    "Golf 5",
    "Golf 6",
    "Golf 7",
    "Golf 8",
    "ID.3",
    "ID.4",
    "ID.5",
    "Jetta",
    "LT",
    "Lupo",
    "Multivan",
    "New Beetle",
    "Parati",
    "Passat",
    "Phaeton",
    "Polo",
    "Scirocco",
    "Sharan",
    "T-Cross",
    "T-Roc",
    "Taigo",
    "Tiguan",
    "Touareg",
    "Touran",
    "Transporter",
    "UP",
    "Vento",
  ],
  Volvo: [
    "240",
    "460",
    "850",
    "C30",
    "C40",
    "Cross Country",
    "S40",
    "S60",
    "S70",
    "S80",
    "S90",
    "V40",
    "V60",
    "V90",
    "XC40",
    "XC60",
    "XC70",
    "XC90",
  ],
  Zotye: ["Nomad"],
};

const marques = Object.keys(dict_marque_modele);

const select_constructor = (field_text, parElement) => {
  const elementParent = document.querySelector(`#${parElement}`);
  const element = document.createElement("option");
  element.setAttribute("value", field_text);
  element.classList.add("option");
  element.textContent = field_text;
  elementParent.append(element);
};

document.querySelector("#marque").addEventListener("change", (e) => {
  document.querySelectorAll('#modele option').forEach((opt)=>opt.remove())
  dict_marque_modele[e.target.value].forEach((modele) => {
    select_constructor(modele, "modele");
  });
});

marques.forEach((marque) => {
  select_constructor(marque, "marque");
});

let annee = 2025;

while (annee > 1980) {
  select_constructor(annee, "annee");
  annee--;
}

document.querySelector('#modele').addEventListener('change',async (e)=>{
   const response = await fetch("https://cotav-back.onrender.com/modele_annee",
    {
      method:'POST',
      headers:{"content-type" : "application/json"},
      body : JSON.stringify({ modele : e.target.value})
    }
   ) ; 

   const result = await response.json()
   
   const annee = document.querySelectorAll('#annee option').forEach(opt=>opt.remove())
   result[e.target.value].forEach(annee=>{select_constructor(annee,'annee')})
   
   console.log()
})


document.querySelector('.nav-button').addEventListener('click',(e)=>{

  const nav_liste  = document.querySelector('.nav-liste')
  nav_liste.classList.toggle('active')
})



